"""add bond terms table

Revision ID: 53ae7d954685
Revises: 2c7e0639e54a
Create Date: 2026-10-07 10:45:32.345855+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ae7d954685'
down_revision: Union[str, Sequence[str], None] = '2c7e0639e54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_bond_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('bond_symbol', sa.String(length=10), nullable=False),
    sa.Column('series_code', sa.String(length=20), nullable=False),
    sa.Column('nominal_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('capitalization', sa.String(length=10), nullable=False),
    sa.Column('first_period_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('margin', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('redemption_fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'bonds'"), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_bond_terms_asset_id'), 'assets_bond_terms', ['asset_id'], unique=True)
    op.create_index(op.f('ix_assets_bond_terms_bond_symbol'), 'assets_bond_terms', ['bond_symbol'], unique=False)
    op.create_index(op.f('ix_assets_bond_terms_id'), 'assets_bond_terms', ['id'], unique=False)
    op.create_index(op.f('ix_assets_bond_terms_series_code'), 'assets_bond_terms', ['series_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_bond_terms_series_code'), table_name='assets_bond_terms')
    op.drop_index(op.f('ix_assets_bond_terms_id'), table_name='assets_bond_terms')
    op.drop_index(op.f('ix_assets_bond_terms_bond_symbol'), table_name='assets_bond_terms')
    op.drop_index(op.f('ix_assets_bond_terms_asset_id'), table_name='assets_bond_terms')
    op.drop_table('assets_bond_terms')
    # ### end Alembic commands ###
