"""Add job_run table for daily refresh locking

Revision ID: 54330902c90c
Revises: 0d1e22a14d76
Create Date: 2026-10-06 17:16:48.194921+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54330902c90c'
down_revision: Union[str, Sequence[str], None] = '0d1e22a14d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_jobrun',
    sa.Column('job_key', sa.String(length=64), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'idle'"), nullable=False),
    sa.PrimaryKeyConstraint('job_key')
    )
    op.create_index(op.f('ix_assets_jobrun_job_key'), 'assets_jobrun', ['job_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_jobrun_job_key'), table_name='assets_jobrun')
    op.drop_table('assets_jobrun')
    # ### end Alembic commands ###
