"""users base currency

Revision ID: 2c7e0639e54a
Revises: 54330902c90c
Create Date: 2026-10-06 20:49:22.283540+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7e0639e54a'
down_revision: Union[str, Sequence[str], None] = '54330902c90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_currency_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'assets_currency', ['base_currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'base_currency_id')
    # ### end Alembic commands ###
