"""portfolios_daily_and_dirty_from

Revision ID: 0d1e22a14d76
Revises: 502da01d1dba
Create Date: 2026-10-04 17:00:53.535259+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1e22a14d76'
down_revision: Union[str, Sequence[str], None] = '502da01d1dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios_daily',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('inflow', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('outflow', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('r_day', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('twr_index', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios_portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'day')
    )
    op.add_column('portfolios_portfolio', sa.Column('dirty_from', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios_portfolio', 'dirty_from')
    op.drop_table('portfolios_daily')
    # ### end Alembic commands ###
