"""operation split ratio

Revision ID: 502da01d1dba
Revises: 2fa662b86ab6
Create Date: 2026-10-04 15:56:52.740538+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502da01d1dba'
down_revision: Union[str, Sequence[str], None] = '2fa662b86ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios_operation', sa.Column('ratio', sa.Numeric(precision=18, scale=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios_operation', 'ratio')
    # ### end Alembic commands ###
