"""rename indexes to default naming

Revision ID: 74834345f4d0
Revises: 78e899c115c6
Create Date: 2026-10-01 21:09:41.643473+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74834345f4d0'
down_revision: Union[str, Sequence[str], None] = '78e899c115c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_assets_asset_id'), table_name='assets_asset')
    op.drop_index(op.f('ix_public_assets_asset_ticker'), table_name='assets_asset')
    op.create_index(op.f('ix_assets_asset_id'), 'assets_asset', ['id'], unique=False)
    op.create_index(op.f('ix_assets_asset_ticker'), 'assets_asset', ['ticker'], unique=True)
    op.drop_index(op.f('ix_public_assets_assetclass_id'), table_name='assets_assetclass')
    op.create_index(op.f('ix_assets_assetclass_id'), 'assets_assetclass', ['id'], unique=False)
    op.drop_index(op.f('ix_public_assets_currency_code'), table_name='assets_currency')
    op.drop_index(op.f('ix_public_assets_currency_id'), table_name='assets_currency')
    op.create_index(op.f('ix_assets_currency_code'), 'assets_currency', ['code'], unique=True)
    op.create_index(op.f('ix_assets_currency_id'), 'assets_currency', ['id'], unique=False)
    op.drop_index(op.f('ix_public_portfolios_operation_id'), table_name='portfolios_operation')
    op.drop_index(op.f('ix_public_portfolios_operation_operation_date'), table_name='portfolios_operation')
    op.create_index(op.f('ix_portfolios_operation_id'), 'portfolios_operation', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_operation_operation_date'), 'portfolios_operation', ['operation_date'], unique=False)
    op.drop_index(op.f('ix_public_portfolios_portfolio_id'), table_name='portfolios_portfolio')
    op.create_index(op.f('ix_portfolios_portfolio_id'), 'portfolios_portfolio', ['id'], unique=False)
    op.drop_index(op.f('ix_public_portfolios_position_id'), table_name='portfolios_position')
    op.create_index(op.f('ix_portfolios_position_id'), 'portfolios_position', ['id'], unique=False)
    op.drop_index(op.f('ix_public_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_portfolios_position_id'), table_name='portfolios_position')
    op.create_index(op.f('ix_public_portfolios_position_id'), 'portfolios_position', ['id'], unique=False)
    op.drop_index(op.f('ix_portfolios_portfolio_id'), table_name='portfolios_portfolio')
    op.create_index(op.f('ix_public_portfolios_portfolio_id'), 'portfolios_portfolio', ['id'], unique=False)
    op.drop_index(op.f('ix_portfolios_operation_operation_date'), table_name='portfolios_operation')
    op.drop_index(op.f('ix_portfolios_operation_id'), table_name='portfolios_operation')
    op.create_index(op.f('ix_public_portfolios_operation_operation_date'), 'portfolios_operation', ['operation_date'], unique=False)
    op.create_index(op.f('ix_public_portfolios_operation_id'), 'portfolios_operation', ['id'], unique=False)
    op.drop_index(op.f('ix_assets_currency_id'), table_name='assets_currency')
    op.drop_index(op.f('ix_assets_currency_code'), table_name='assets_currency')
    op.create_index(op.f('ix_public_assets_currency_id'), 'assets_currency', ['id'], unique=False)
    op.create_index(op.f('ix_public_assets_currency_code'), 'assets_currency', ['code'], unique=True)
    op.drop_index(op.f('ix_assets_assetclass_id'), table_name='assets_assetclass')
    op.create_index(op.f('ix_public_assets_assetclass_id'), 'assets_assetclass', ['id'], unique=False)
    op.drop_index(op.f('ix_assets_asset_ticker'), table_name='assets_asset')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets_asset')
    op.create_index(op.f('ix_public_assets_asset_ticker'), 'assets_asset', ['ticker'], unique=True)
    op.create_index(op.f('ix_public_assets_asset_id'), 'assets_asset', ['id'], unique=False)
    # ### end Alembic commands ###
