"""Initial

Revision ID: 78e899c115c6
Revises: 
Create Date: 2026-05-24 19:30:35.690094+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e899c115c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_assetclass',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_assets_assetclass_id'), 'assets_assetclass', ['id'], unique=False, schema='public')
    op.create_table('assets_currency',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('base_currency_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['public.assets_currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_assets_currency_code'), 'assets_currency', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_assets_currency_id'), 'assets_currency', ['id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_table('assets_asset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_class_id', sa.BigInteger(), nullable=False),
    sa.Column('currency_id', sa.BigInteger(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_class_id'], ['public.assets_assetclass.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['public.assets_currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_assets_asset_id'), 'assets_asset', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_assets_asset_ticker'), 'assets_asset', ['ticker'], unique=True, schema='public')
    op.create_table('portfolios_portfolio',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency_id', sa.BigInteger(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['public.assets_currency.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='unique_portfolio_per_user'),
    schema='public'
    )
    op.create_index(op.f('ix_public_portfolios_portfolio_id'), 'portfolios_portfolio', ['id'], unique=False, schema='public')
    op.create_table('portfolios_operation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('operation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['public.assets_asset.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['public.portfolios_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_operation_portfolio_date', 'portfolios_operation', ['portfolio_id', 'operation_date'], unique=False, schema='public')
    op.create_index(op.f('ix_public_portfolios_operation_id'), 'portfolios_operation', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_portfolios_operation_operation_date'), 'portfolios_operation', ['operation_date'], unique=False, schema='public')
    op.create_table('portfolios_position',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('average_fx_rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_dividends', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['public.assets_asset.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['public.portfolios_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='unique_position_per_portfolio'),
    schema='public'
    )
    op.create_index('ix_position_portfolio_asset', 'portfolios_position', ['portfolio_id', 'asset_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_portfolios_position_id'), 'portfolios_position', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_portfolios_position_id'), table_name='portfolios_position', schema='public')
    op.drop_index('ix_position_portfolio_asset', table_name='portfolios_position', schema='public')
    op.drop_table('portfolios_position', schema='public')
    op.drop_index(op.f('ix_public_portfolios_operation_operation_date'), table_name='portfolios_operation', schema='public')
    op.drop_index(op.f('ix_public_portfolios_operation_id'), table_name='portfolios_operation', schema='public')
    op.drop_index('ix_operation_portfolio_date', table_name='portfolios_operation', schema='public')
    op.drop_table('portfolios_operation', schema='public')
    op.drop_index(op.f('ix_public_portfolios_portfolio_id'), table_name='portfolios_portfolio', schema='public')
    op.drop_table('portfolios_portfolio', schema='public')
    op.drop_index(op.f('ix_public_assets_asset_ticker'), table_name='assets_asset', schema='public')
    op.drop_index(op.f('ix_public_assets_asset_id'), table_name='assets_asset', schema='public')
    op.drop_table('assets_asset', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_assets_currency_id'), table_name='assets_currency', schema='public')
    op.drop_index(op.f('ix_public_assets_currency_code'), table_name='assets_currency', schema='public')
    op.drop_table('assets_currency', schema='public')
    op.drop_index(op.f('ix_public_assets_assetclass_id'), table_name='assets_assetclass', schema='public')
    op.drop_table('assets_assetclass', schema='public')
    # ### end Alembic commands ###
