"""portfolios import tables

Revision ID: 2fa662b86ab6
Revises: 5e76e12c6a9e
Create Date: 2026-10-03 19:27:54.948727+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fa662b86ab6'
down_revision: Union[str, Sequence[str], None] = '5e76e12c6a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios_import_batch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('parser_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios_portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sha256', name='uq_import_batch_owner_sha256')
    )
    op.create_index('ix_import_batch_owner_portfolio', 'portfolios_import_batch', ['owner_id', 'portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolios_import_batch_id'), 'portfolios_import_batch', ['id'], unique=False)
    op.create_table('portfolios_import_row',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets_asset.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['portfolios_import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['portfolios_operation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_row_batch', 'portfolios_import_row', ['batch_id', 'row_number'], unique=False)
    op.create_index(op.f('ix_portfolios_import_row_id'), 'portfolios_import_row', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_import_row_operation_id'), 'portfolios_import_row', ['operation_id'], unique=False)
    op.add_column('portfolios_operation', sa.Column('external_ref', sa.String(length=120), nullable=True))
    op.add_column('portfolios_operation', sa.Column('import_batch_id', sa.BigInteger(), nullable=True))
    op.add_column('portfolios_operation', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_portfolios_operation_import_batch_id'), 'portfolios_operation', ['import_batch_id'], unique=False)
    op.create_index('uq_operation_portfolio_external_ref', 'portfolios_operation', ['portfolio_id', 'external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.create_foreign_key('fk_operation_import_batch_id', 'portfolios_operation', 'portfolios_import_batch', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_operation_import_batch_id', 'portfolios_operation', type_='foreignkey')
    op.drop_index('uq_operation_portfolio_external_ref', table_name='portfolios_operation', postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.drop_index(op.f('ix_portfolios_operation_import_batch_id'), table_name='portfolios_operation')
    op.drop_column('portfolios_operation', 'edited_at')
    op.drop_column('portfolios_operation', 'import_batch_id')
    op.drop_column('portfolios_operation', 'external_ref')
    op.drop_index(op.f('ix_portfolios_import_row_operation_id'), table_name='portfolios_import_row')
    op.drop_index(op.f('ix_portfolios_import_row_id'), table_name='portfolios_import_row')
    op.drop_index('ix_import_row_batch', table_name='portfolios_import_row')
    op.drop_table('portfolios_import_row')
    op.drop_index(op.f('ix_portfolios_import_batch_id'), table_name='portfolios_import_batch')
    op.drop_index('ix_import_batch_owner_portfolio', table_name='portfolios_import_batch')
    op.drop_table('portfolios_import_batch')
    # ### end Alembic commands ###
