"""assets price and fx rate history, asset identifiers and archive

Revision ID: e5378aa1fa93
Revises: 74834345f4d0
Create Date: 2026-10-02 19:01:06.699947+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5378aa1fa93'
down_revision: Union[str, Sequence[str], None] = '74834345f4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_fx_rate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_currency_id', sa.BigInteger(), nullable=False),
    sa.Column('to_currency_id', sa.BigInteger(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('table_no', sa.String(length=32), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_currency_id <> to_currency_id', name='ck_assets_fx_rate_distinct'),
    sa.CheckConstraint('rate > 0', name='ck_assets_fx_rate_rate_positive'),
    sa.ForeignKeyConstraint(['from_currency_id'], ['assets_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency_id'], ['assets_currency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_id', 'to_currency_id', 'rate_date', 'source', name='uq_assets_fx_rate_pair_date_source')
    )
    op.create_index('ix_assets_fx_rate_pair_rate_date', 'assets_fx_rate', ['from_currency_id', 'to_currency_id', 'rate_date'], unique=False)
    op.create_table('assets_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('currency_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('close > 0', name='ck_assets_price_close_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets_asset.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['assets_currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', 'source', name='uq_assets_price_asset_date_source')
    )
    op.create_index('ix_assets_price_asset_id_price_date', 'assets_price', ['asset_id', 'price_date'], unique=False)
    op.add_column('assets_asset', sa.Column('isin', sa.String(length=12), nullable=True))
    op.add_column('assets_asset', sa.Column('mic', sa.String(length=4), nullable=True))
    op.add_column('assets_asset', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('assets_asset', sa.Column('asset_type', sa.String(length=20), server_default=sa.text("'user_asset'"), nullable=False))
    op.add_column('assets_asset', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_assets_asset_asset_type'), 'assets_asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_asset_isin'), 'assets_asset', ['isin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_asset_isin'), table_name='assets_asset')
    op.drop_index(op.f('ix_assets_asset_asset_type'), table_name='assets_asset')
    op.drop_column('assets_asset', 'archived_at')
    op.drop_column('assets_asset', 'asset_type')
    op.drop_column('assets_asset', 'country')
    op.drop_column('assets_asset', 'mic')
    op.drop_column('assets_asset', 'isin')
    op.drop_index('ix_assets_price_asset_id_price_date', table_name='assets_price')
    op.drop_table('assets_price')
    op.drop_index('ix_assets_fx_rate_pair_rate_date', table_name='assets_fx_rate')
    op.drop_table('assets_fx_rate')
    # ### end Alembic commands ###
