# Generated by Django 5.0.6 on 2026-02-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cash_balance', models.DecimalField(decimal_places=3, default=0, help_text='Available cash', max_digits=18)),
                ('total_deposited', models.DecimalField(decimal_places=3, default=0, help_text='Total deposits - withdrawals', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pockets', to='assets.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=9, default=0, max_digits=18)),
                ('average_buy_price', models.DecimalField(decimal_places=9, default=0, help_text='Weighted average purchase price in asset currency', max_digits=18)),
                ('average_fx_rate', models.DecimalField(decimal_places=9, default=1, help_text='Weighted average FX rate at purchase time', max_digits=18)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='assets.asset')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolios.pocket')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='pocket',
            name='assets',
            field=models.ManyToManyField(blank=True, through='portfolios.Position', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit Cash'), ('withdrawal', 'Withdraw Cash'), ('dividend', 'Dividend')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=9, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=9, default=0, max_digits=18)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fx_rate', models.DecimalField(decimal_places=9, default=1, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('operation_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.asset')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oerations', to='portfolios.pocket')),
            ],
            options={
                'ordering': ['-operation_date'],
                'indexes': [models.Index(fields=['pocket', '-operation_date'], name='portfolios__pocket__4b11a1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['pocket', 'asset'], name='portfolios__pocket__e9fb3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('pocket', 'asset'), name='unique_position_per_pocket'),
        ),
        migrations.AddConstraint(
            model_name='pocket',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_pocket_per_user'),
        ),
    ]
